version: "3.9"

networks:
  rate-limiter-net:
    driver: bridge

services:
  rate-limiter:
    container_name: rate-limiter
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - rate-limiter-net
